apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: "public"
spec:
  type: LoadBalancer
  selector:
    app: guestbook-ui
  ports:
  - port: 80
    targetPort: 80

 
