apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-load-balancer
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: "public"
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
 type: LoadBalancer
