apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-baskets-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: request-baskets-ui
  template:
    metadata:
      labels:
        app: request-baskets-ui
    spec:
      containers:
      - image: darklynx/request-baskets
        name: request-baskets
        ports:
        - containerPort: 55555
---
apiVersion: v1
kind: Service
metadata:
  name: request-baskets-ui
spec:
  selector:
    app: request-baskets-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 55555
  type: LoadBalancer
